- 09-2023(sep)/06-sep.cpp
The Last loop in the function findMotherFunction is not required
> Corrected the code

- 10-2023(oct)/11-oct.cpp
Solved GFG POTD of 11th October 2023
> Created 11-oct.cpp

- 10-2023(oct)/12-oct.cpp
Solved GFG POTD (12th October) in C++
> Created 12-oct.cpp

- 10-2023(oct)/12 - Duplicate subtree in Binary Tree.md
Added .md file for 12th October
> Create 12 - Duplicate subtree in Binary Tree.md

- 10-2023(oct)/13-oct.cpp
Solved GFG POTD (13th Oct) in C++
> Created 13-oct.cpp

- 10-2023(oct)/13 - Floor in BST.md
Added .md file for GFG POTD (13th Oct)
> Create 13 - Floor in BST.md

- 10-2023(oct)/19 - Level of Nodes.md
- 10-2023(oct)/19-oct.cpp
Note - You have written the name of "2-oct.cpp" and "18-oct.cpp" as "2-sep.cpp" and "18-sep.cpp"
> Added 19 Oct GFG POTD solution and md file

- 2024/03-2024(march)/05 - Maximum Index.md
- 2024/03-2024(march)/05-march.cpp
- README.md
Additionaly I have also modified the README.md file for today's POTD
> Added solution and md file for GFG POTD (05/03/2024)

- 2024/03-2024(march)/09 - Find the N-th character.md
- 2024/03-2024(march)/09-march.cpp
- README.md
Additionaly, I have also updated the README.md file
> Added solution and md file for GFG POTD (09/03/2024)

- 2024/03-2024(march)/20 - Sum of nodes on the longest path from root to leaf node.md
- 2024/03-2024(march)/20-march.cpp
- README.md
Additionaly I have also edited the main README.md file
> Added solution and md file for GFG POTD (20/03/2024)

- 2024/03-2024(march)/21 - ZigZag Tree Traversal.md
- 2024/03-2024(march)/21-march.cpp
- README.md
Additionaly I have also updated the main README.md file
> Added solution and md file for GFG POTD (21/03/2024)

- 2024/03-2024(march)/22 - Diagonal sum in binary tree.md
- 2024/03-2024(march)/22 - march.cpp
- README.md
Additionaly I have also edited the README.md file accordingly
> Added solution and md file for GFG POTD (22/03/2024)

- 2024/03-2024(march)/22 - Fibonacci series up to Nth term.md
- 2024/03-2024(march)/23 - Fibonacci series up to Nth term.md
- 2024/03-2024(march)/23 - march.cpp
- 2024/03-2024(march)/24 - Insert an Element at the Bottom of a Stack.md
- 2024/03-2024(march)/24 - march.cpp
- README.md
Additionaly I have also updated the README.md file accordingly
> Added solution and md file for GFG POTD (23/03/2024 & 24/03/2024)

- 2024/03-2024(march)/29 - Euler Circuit in an Undirected Graph.md
- 2024/03-2024(march)/29-march.cpp
- README.md
Additionaly I have also changed the README.md file accordingly
> Added solution and md file of GFG POTD (29/03/2024)

- 2024/03-2024(march)/30 - Minimum element in BST.md
- 2024/03-2024(march)/30-march.cpp
- README.md
Additionaly I have also updated the README.md file accordingly
> Added solution and md file for GFG POTD (30/03/2024)

- 2023/07-2023(july)/04 - Count the subarrays having product less than k.md
Your previous solution was not working for two very complex bigger test cases. Now my proposed solution is working for all the test cases.
> Update 04 - Count the subarrays having product less than k.md

- 2023/06-2023(june)/02 - Santa Banta.md
Your earlier code was showing segmentation error. This updated one is working for all the test cases.
> Update 02 - Santa Banta.md

- 2024/04-2024(april)/10 - Party of Couples.md
- 2024/04-2024(april)/10-april.cpp
- README.md
Additionally I have also updated the main README.md file accordingly
> Added solution and md file for GFG POTD (10/04/2024)

- 2024/04-2024(april)/14 - Xoring and Clearing.md
- 2024/04-2024(april)/14-april.cpp
- README.md
Additionally I have also updated the main README.md file accordingly
> Added solution and md file for GFG POTD (14/04/2024)

- 2024/04-2024(april)/20 - Union of Two Sorted Arrays.md
- 2024/04-2024(april)/20-april.cpp
- README.md
Additionally I have also updated the README.md file accordingly
> Added solution and md file for GFG POTD (20/04/2024)

- 2024/04-2024(april)/23 - Rohan's Love for Matrix.md
- 2024/04-2024(april)/23-april.cpp
- README.md
Additionally I have also updated the README.md file accordingly
> Added solution and md file for GFG POTD (23/04/2024)

- 2024/04-2024(april)/28 - Delete Middle of Linked List.md
- 2024/04-2024(april)/28-april.cpp
- README.md
Additionally I have also updated the README.md file accordingly
> Added solution and md file for GFG POTD (28/04/2024)

- 2024/04-2024(april)/28 - Delete Middle of Linked List.md
- 2024/04-2024(april)/29 - Remove every kth node.md
- 2024/04-2024(april)/29-april.cpp
- README.md
Additionally I have also updated the README.md file accordingly and have also updated a date error in 28th POTD md file
> Added solution and md file for GFG POTD (29/04/2024)

- 2024/05-2024(may)/03 - K distance from root.md
- 2024/05-2024(may)/03-May.cpp
- README.md
> Added solution and md file for GFG POTD (03/05/2024)

- 2024/05-2024(may)/06 - Print all nodes that don't have sibling.md
- 2024/05-2024(may)/06-May.cpp
- README.md
> Added solution and md file for GFG POTD (06/05/2024)

- 2024/05-2024(may)/17 - Find Pair Given Difference.md
- 2024/05-2024(may)/17-may.cpp
- README.md
> Added solution and md file for GFG POTD (17/05/2024)

- 2024/05-2024(may)/18 - Find the Highest number.md
- 2024/05-2024(may)/18-may.cpp
- README.md
> Added solution and md file for GFG POTD (18/05/2024)

- 2024/05-2024(may)/19 - Find the closest number.md
- 2024/05-2024(may)/19-may.cpp
- README.md
> Added solution and md file for GFG POTD (19/05/2024)

- 2024/05-2024(may)/20 - Modular Exponentiation for large numbers.md
- 2024/05-2024(may)/20-may.cpp
- README.md
> Added solution and md file for GFG POTD (20/05/2024)

- 2024/05-2024(may)/23 - K-Palindrome.md
- 2024/05-2024(may)/23-may.cpp
- 2024/05-2024(may)/24 - Partitions with Given Difference.md
- 2024/05-2024(may)/24-may.cpp
- 2024/05-2024(may)/26 - Minimum Cost To Make Two Strings Identical.md
- 2024/05-2024(may)/26-may.cpp
- 2024/05-2024(may)/28 - Minimum cost to fill given weight in a bag.md
- 2024/05-2024(may)/28-may.cpp
- README.md
> Added solution and md file for GFG POTD (23/05/2024, 24/05/2024, 26/05/2024 and 28/05/2024)

- 2024/06-2024(june)/05-june.cpp
- 2024/06-2024(june)/06-june.cpp
- 2024/06-2024(june)/07-june.cpp
- 2024/06-2024(june)/08-june.cpp
- 2024/06-2024(june)/09-june.cpp
- 2024/06-2024(june)/10-june.cpp
- 2024/06-2024(june)/11-june.cpp
- 2024/06-2024(june)/12-june.cpp
- 2024/06-2024(june)/13-june.cpp
- 2024/06-2024(june)/14-june.cpp
- 2024/06-2024(june)/15-june.cpp
I have not added the README.md files for the same
> Added solution and md file for GFG POTD (05/06/2024 to 15/16/2024)

- 2024/06-2024(june)/16-june.cpp
- 2024/06-2024(june)/17-june.cpp
- 2024/06-2024(june)/18-june.cpp
- 2024/06-2024(june)/19-june.cpp
- 2024/06-2024(june)/20-june.cpp
- 2024/06-2024(june)/21-june.cpp
- 2024/06-2024(june)/22-june.cpp
- 2024/06-2024(june)/23-june.cpp
- 2024/06-2024(june)/24-june.cpp
- 2024/06-2024(june)/25-june.cpp
- 2024/06-2024(june)/26-june.cpp
- 2024/06-2024(june)/27-june.cpp
- 2024/06-2024(june)/28-june.cpp
- 2024/06-2024(june)/29 - Identical Linked Lists.md
- 2024/06-2024(june)/29-june.cpp
- README.md
> Added solution and md file for GFG POTD (16/06/2024 to 29/16/2024)

- 2024/06-2024(june)/30 - Delete node in Doubly Linked List.md
- 2024/06-2024(june)/30-june.cpp
- README.md
> Added solution and md file for GFG POTD (30/05/2024)
